#!/bin/sh
# УЛТЙРФ ОБРЙУБО id00024 (c)

#DLC=/usr/dlc/bin; export DLC
#PATH=$DLC:/usr/local/bin:/bin:/usr/bin:/pragma/bin9/protop/bin:/pragma/bin9/; export PATH

#echo "$PATH" >> /tmp/123.log

#/pragma/bin9/dbchck /data/bchm/bank  >> /tmp/123.log

#echo "/usr/dlc/bin/_dbutil /data/bchm/bank -C holder >> /tmp/asa.txt " >> /tmp/asa.txt 
#/usr/dlc/bin/_dbutil /data/bchm/bank -C holder >> /tmp/asa.txt
#echo "code=$?" >> /tmp/asa.txt
#!/bin/sh
# бЄаЁЇв ­ ЇЁб ­ id00024 (c)

ME=`/usr/bin/whoami`
export ME

SOURS=`ps -eaf | grep $ME | grep $1 | grep _progres | awk '{print $1" "$9}' | grep bank | awk '{print $2}'`
BASE=`echo -n "$SOURS" | awk -F/ '{print $3}'`

if [ "$BASE" = "$1" ]
 then
clear
while true
do
  echo
  echo "уЕТЧЕТ ПВОПТХЦЙМ ЮФП чБЫ МПЗЙО ($ME) ХЦЕ РПДЛМАЮЕО Л ВБЪЕ ДБООЩИ бп 'нефтплпнвболБ'"
  echo "уЛПТЕЕ ЧУЕЗП РТПЙЪПЫМП ПФЛМАЮЕОЙЕ УЧСЪЙ"
  echo "рПДФЧЕТДЙФЕ ЧИПД Ч ВБЪХ ДБООЩИ:"
  echo
  echo "1) чПКФЙ Ч ВБЪХ ДБООЩИ бп 'нефтплпнвболБ'"
  echo "2) чЩКФЙ ЙЪ ЬФПЗП НЕОА"
  echo
  read ans
  case $ans in
  1) pragma $1;;
  2) exit;;
  *) echo "рПЦБМХКУФБ ОБЦНЙФЕ ГЙЖТХ 1 ЙМЙ 2, ЪБФЕН ЛМБЧЙЫХ ENTER"; sleep 2;;
  esac
done
   else
  pragma $1
fi
