#!/bin/sh
DLC=/usr/dlc; export DLC
$DLC/bin/_dbutil $1 -C holder

case $? in 
0) echo "Database $1 is not in use. Code: $?";; 
14) echo "Database $1 is in use in single-user mode. Code: $?";; 
#16) echo "Database $1 is in use in multi-user mode. Code: $?";; 
16) ;; 
*) echo "Database $1: Unknown error. Code: $?";; 
esac