#!/bin/sh
# УЛТЙРФ ОБРЙУБО id00024 (c)

TIME=`date "+%d-%m-%y"`
 

ID=$1
. /pragma/bin9/dbenv 




while true
do  
  echo    
  echo 
  echo "    1. Run DAYCLOSE on $DBDESCR"
  echo "    2. Run NEWMONTH on $DBDESCR"
  echo "    Q. EXIT"
  echo 
  echo 
  read ans
  case $ans in
  1)
  /usr/dlc/bin/_dbutil $DBDIR/$DBNAME -C holder > /tmp/as.txt 
   if [ "$?" = "0" ]
     then
	rfutil $DBDIR/$DBNAME -C aimage end
       
        $DLC/bin/_mprosrv $DBDIR/$DBNAME  -i -L 65000 -spin 16000 -n 4 -Mxs 250 
        $DLC/bin/probiw   $DBDIR/$DBNAME
        $DLC/bin/proapw   $DBDIR/$DBNAME
        $DLC/bin/proapw   $DBDIR/$DBNAME

        echo; echo -n "Press enter to continue dayclose on $DBDESCR | Ctrl+C to abort."
        read ANS
	echo "Contining!"
	sleep 2
	
        cd /data/log/$DBID
	$DLC/bin/_progres $DBDIR/$DBNAME -clientlog $DBDIR/log/logdayclose/dayclose-$TIME.log -logginglevel 4 -p dayclose -trig $PTRIGLIB -U bankadm -P $passw -t 

        cd ..
        $DLC/bin/_mprshut $DBDIR/$DBNAME  -by

     else
       echo "Cannot run dayclose. Database $DBDESCR is still started!" 
     fi
     ;; 
  2) 
       $DLC/bin/_progres $DBDIR/$DBNAME -clientlog $DBDIR/newmonth.log -logginglevel 4 -1 -i -L 2000 -d dmy -p newmonth -trig $PTRIGLIB -U bankadm -P $passw
       ;;
 [Qq]) exit 0;;
  exit) exit 0;;
  *) echo "Wrong selection. Press 1-2 or Q."
     sleep 1;;
  esac
done

else 
echo "\nPassword incorrect!"
fi
