#!/bin/sh
# УЛТЙРФ ОБРЙУБО id00024 (c)

TIME=`date "+%d-%m-%y"`


ID=$1
. /pragma/bin9/dbenv 




while true
do  
  echo    
  echo 
  echo "    1. Start $DBDESCR database server (BANK, ALGA)"
  echo "    2. Stop $DBDESCR database server (BANK, ALGA)"
  echo "    Q. EXIT"
  echo 
  echo 
  read ans
  case $ans in
  1) 
  /usr/dlc/bin/_dbutil $DBDIR/$DBNAME -C holder > /tmp/as.txt 
   if [ "$?" = "0" ]
     then
 	echo "Truncating AI on $DBDESCR..."
	$DLC/bin/rfutil $DBDIR/$DBNAME -C aimage truncate -G 0

	echo; echo "Start Aftar Image on $DBDESCR + truncate bi"
	rfutil $DBDIR/$DBNAME -C aimage begin

        $DLC/bin/_mprosrv $DBDIR/$DBNAME -Mn 21 -n 100 -B 15000 -L 20000 -bibufs 25 -trig $PTRIGLIB -semsets 1 -spin 10000 -bithold 650 -bistall || echo Cannot start server.

       $DLC/bin/_mprosrv $DBDIR/$DBNAME -m3 -N TCP -S $DBSV -Mm 16300 -Mpb 20 -Ma 5 -Mi 3 $MINPORT $MAXPORT 
       $DLC/bin/prowdog  $DBDIR/$DBNAME
       $DLC/bin/probiw   $DBDIR/$DBNAME
       $DLC/bin/proaiw   $DBDIR/$DBNAME
       $DLC/bin/proapw   $DBDIR/$DBNAME
       $DLC/bin/proapw   $DBDIR/$DBNAME
	rm $DBDIR/.lock-b

     else
       echo Cannot DO THIS. 
     fi
	;;
  2)
  /usr/dlc/bin/_dbutil $DBDIR/$DBNAME -C holder > /tmp/as.txt 
   if [ "$?" = "16" ]
     then
	dbshut $DBDIR/$DBNAME
	touch $DBDIR/.lock-b
#	rfutil $DBDIR/$DBNAME -C aimage end
     else
       echo Cannot DO THIS. 
     fi
	;;
 [Qq]) exit 0;;
  exit) exit 0;;
  *) echo "Wrong selection. Press 1-8 or Q."
     sleep 1;;
  esac
done

else 
echo "\nPassword incorrect!"
fi
