#!/bin/sh

# фпп тлг-1
/pragma/bin9/watchcat rkc

# нлп ТБВПЮЙЕ ВБЪЩ
/pragma/bin9/watchcat alm
/pragma/bin9/watchcat akt
/pragma/bin9/watchcat kos
/pragma/bin9/watchcat trz
/pragma/bin9/watchcat url
/pragma/bin9/watchcat kar
/pragma/bin9/watchcat sem
/pragma/bin9/watchcat kok
/pragma/bin9/watchcat ast

# нефтплпнвбол ТБВПЮЙЕ ВБЪЩ
/pragma/bin9/watchcat balm
/pragma/bin9/watchcat bakt
/pragma/bin9/watchcat bkos
/pragma/bin9/watchcat btrz
/pragma/bin9/watchcat burl
/pragma/bin9/watchcat bkar
/pragma/bin9/watchcat bsem
/pragma/bin9/watchcat bkok
/pragma/bin9/watchcat bast

# нефтплпнвбол жЙМЙБМЩ ОБ УФБДЙЙ ПФЛТЩФЙС
#/pragma/bin9/watchcat bpav
#/pragma/bin9/watchcat bpet
#/pragma/bin9/watchcat batr
#/pragma/bin9/watchcat baku
#/pragma/bin9/watchcat bzes
#/pragma/bin9/watchcat bust
#/pragma/bin9/watchcat bchm

# пВЭЙЕ ВБЪЩ ТБВПФБАЭЙЕ 24/7
/pragma/bin9/watchcat comm
/pragma/bin9/watchcat cards

#END
#OK