#!/bin/bash

#lst='/usr/etc/cptwin.ssh'

#touch $log

# всем понятно
test $pc || { export pc=`/usr/local/bin/askhost`; }
#pc=$USERHOST

log="/data/log/cptwin/$pc"
touch $log

echo "[`date +"%Y/%m/%d-%H:%M:%S"`] --------" >> $log

#if [ `echo $pc | grep -c -i -F -f - $lst` -gt 0 ]; then
 #
 # It is one from SSH ready host listed in $lst
 rdir='c:/tmp'
 rfil=$$.`echo $1 | awk '{D=split($0,M,"."); print M[D] }'`
 /pragma/bin9/un-win $1 $rfil
 echo "[`date +"%Y/%m/%d-%H:%M:%S"`] SSH: rfil=$rfil" >> $log
 echo -n "[`date +"%Y/%m/%d-%H:%M:%S"`] SSH: SCP $rfil to $pc ... " >> $log
 scp -q $rfil Administrator@$pc:$rdir/$rfil 1>/dev/null 2>>$log
 if test $? != 0; then
  echo "[FAIL]" >> $log
  echo "[`date +"%Y/%m/%d-%H:%M:%S"`] SSH: scp -q $rfil Administrator@$pc:$rdir/$rfil 1>/dev/null 2>/dev/null" >> $log
  exit 1
 else
  echo "[OK]" >> $log
 fi
 
 # берем третий параметр, делаем из списка с запятыми список с пробелами и в цикле
 # по новому списку заливаем на клиента

 if test $3; then
     files=`echo $3 | tr "," " "`
     for i in $files; do
        scp -q $i Administrator@$pc:$rdir/$i
	 echo "[`date +"%Y/%m/%d-%H:%M:%S"`] scp -q $i Administrator@$pc:$rdir/$i" >> $log
     done
 fi
 
 echo "start $2 c:\\tmp\\${rfil}" > run.cmd
 echo -n "[`date +"%Y/%m/%d-%H:%M:%S"`] SSH: SCP run.cmd to $pc ... " >> $log
 scp -q run.cmd Administrator@$pc:$rdir/run.cmd 1>/dev/null 2>>$log
 if test $? != 0; then
  echo "[FAIL]" >> $log
  echo "[`date +"%Y/%m/%d-%H:%M:%S"`] SSH: scp -q $rfil Administrator@$pc:$rdir/$rfil 1>/dev/null 2>/dev/null" >> $log
  exit 1
 else
  echo "[OK]" >> $log
 fi
 sleep 2
#echo "---" >> $log
rm -f $rfil
exit
