#!/bin/bash

# всем понятно
test $pc || { export pc=`/usr/local/bin/askhost`; }

# берем переменную %TEMP% с хоста $pc и отрезаем досовский перевод строки
RHOST=`ssh $pc echo %TEMP% | tr -d '\15'`

# берем первый параметр скрипта, отрезаем то что после последней точки, 
# и составляем новое имя файла "типа случайное число"+точка+"то что ранее отрезали"
rfil=$$.`echo $1 | awk '{D=split($0,M,"."); print M[D] }'`

# suchkov - Тут я добавил копирование и перекодировку старого файла KOI-8 в новый WIN1251
un-win $1 $rfil

# понятно


# берем третий параметр, делаем из списка с запятыми список с пробелами и в цикле
# по новому списку заливаем на клиента

if test $3; then
     files=`echo $3 | tr "," " "`
     for i in $files; do
        scp $i $pc:$RHOST
     done
fi 

scp $rfil $pc:$RHOST && ssh $pc start $2 $RHOST\\$rfil
rm -f $rfil

