#!/bin/bash

# всем понятно
test $pc || { export pc=`/usr/local/bin/askhost`; }

# берем переменную %TEMP% с хоста $pc и отрезаем досовский перевод строки
RHOST=`rsh $pc echo %TEMP% | tr -d '\15'`

# берем первый параметр скрипта, отрезаем то что после последней точки, 
# и составляем новое имя файла "типа случайное число"+точка+"то что ранее отрезали"
rfil=$$.`echo $1 | awk '{D=split($0,M,"."); print M[D] }'`

cp $1 $rfil
# понятно
rcp $rfil $pc:$RHOST

# берем третий параметр, делаем из списка с запятыми список с пробелами и в цикле
# по новому списку заливаем на клиента

if test $3; then
     files=`echo $3 | tr "," " "`
     for i in $files; do
        rcp $i $pc:$RHOST
     done
fi


rsh $pc start $2 $RHOST\\$rfil
rm -f $rfil

