#!/bin/sh

##/pragma/bin9/dbbackup $DB $CPDIR2(data/fil/backup/)

PATH=/pragma/bin9:$PATH; export PATH
. proenv

#LOG2=`dirname $1`/log/dcls.log
LOG2=/data/log/$DBID/`basename $1 .db`-backup.log
wlog(){
    echo `date "+%d/%m/%y %H:%M:%S"` `whoami` " " $1 $2 $3 $4 |tee -a $LOG2
}

HELP="Usage: "`basename $0`" database [store]\nBackups database to store (default database.Z).\nTo restore database use dbrest."

test -n "$1" || { echo "You must supply a database name."; echo $HELP; exit 1; }
DB=`dirname $1`/`basename $1 .db`
test -f $DB.db || { echo "File $DB.db not found."; echo $HELP; exit 1; }

BAK=${2:-$DB}
BAK=`dirname $BAK`/`basename $BAK .Z`

LOG=backup$DBID.log

echo '***********************************************' >>$LOG
(
#echo `date '+%m/%d/%y %H:%M:%S'` Backup datatabase $DB started by `who -qm`
wlog Start Backup $DB
#dbshut $DB
if [ $? -ne 0 ]; then
  wlog "Backup $DB cancelled due shutdown error."
    exit 2
    fi

rm /tmp/$DBID.tome
for i in `echo '1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z' | awk '{print $0}'`; do echo $BAK$i >> /tmp/$DBID.tome ; done
                    
tome1=$BAK"0"

$DLC/bin/probkup $DB $tome1 -vs 262143 -verbose < /tmp/$DBID.tome; RCODE=$?

if [ $RCODE -ne 0 ]
then
DATE=`date "+%Y/%m/%d-%H:%M:%S"`
echo "Offline Backup of $DB didn't done well. Time = $DATE" | /bin/mail -s Backup 'id00477@forteban.com id00700@fortebank.com id00640@fortebank.com'
fi


#ls -al $BAK* > /tmp/$DB.size
#gzip -1 $BAK* &
#compress <$PIPEFILE >$BAK
#gzip -1 <$PIPEFILE >$BAK
#rm -f $PIPEFILE
wlog End compress $DB 

ls -l $BAK*|awk '{print $9 "\t" $7 " " $6 " " $8 " " $5}'
) 2>&1 | tee -a $LOG
