#!/bin/bash

for i in `echo "bmkb balm bakt bkos btrz burl bkar bsem bkok bast bpet batr bpav bust bzes bchm baku alm akt kos url sem"`
#for i in `echo "bmkb balm bakt bkos btrz burl bkar bsem bkok bast bpet batr bpav bust bzes bchm baku alm akt kos url sem"`
do 
scp -o PasswordAuthentication=no -o batchmode=no /drbd/data/log/$i/login.*.05.2011.* /drbd/home/bankadm/qwe/$i/
done