#!/bin/bash
# 04/12/01 Koval Igor, Parser MT102 (swift.txt)
cat /tmp/$1.txt | tr -d '\015' | awk '
 /:21:/{printf ("%4d\|%4s",NR,substr($0,5,length($0)-4))}
 /:70:\/OPV\/C/ {printf ("\|%16s\|",substr($0,11,length($0)-10))}
 /\/\/FM\//,/\/\/NM\// {
        tempstr = substr($0,6,length($0)-5)
     z = split(tempstr,M,"/"); printf ("%s",M[z])
     }
 /\/\/FT\// {
     tempstr = substr($0,6,length($0)-5)
     z = split(tempstr,M,"/"); printf ("%s",M[z])
     }
 /\/\/DT\// {printf ("\%s\n",substr($0,12,2) substr($0,10,2) substr($0,6,4))}
'> /tmp/${1}.sik

cat /tmp/$1.txt | tr -d '\015' | awk '
  /\{1:/        {print NR "\|1\|" substr($0,4,length($0)-4)}
  /\{2:/        {print NR "\|2\|" substr($0,4,length($0)-4)}
  /:20:/        {print NR "\|20\|" substr($0,5,length($0)-4)}
  /:50:\/D\//   {print NR "\|D\|" substr($0,8,9)}
  /\/RNN\//     {if (NR<10) { print NR "\|RNNORG\|" substr($0,6,12) }
                       else { if (NR<20) { print NR "\|RNN\|" substr($0,6,12) }
                      }
          }        
  /\/NAME\//    {if (NR<10) { print NR "\|NAMEORG\|" substr($0,7,length($0)-6)}
                       else { print NR "\|NAME\|" substr($0,7,length($0)-6)}
             }
  /\/CHIEF\//   {print NR "\|CHIEF\|" substr($0,8,length($0)-7)}
  /\/MAINBK\//  {print NR "\|MAINBK\|" substr($0,9,length($0)-8)}
  /\/IRS\//     {if (NR<12) { print NR "\|IRSORG\|" substr($0,6,length($0)-5)}
                       else { print NR "\|IRS\|" substr($0,6,length($0)-5)}
                }
  /\/SECO\//    {if (NR<14) { print NR "\|SECOORG\|" substr($0,7,length($0)-6)}
                       else { print NR "\|SECO\|" substr($0,7,length($0)-6)} 
                }
  /:52B:/       {print NR "\|52B\|" substr($0,6,9)}
  /:54C:/       {print NR "\|54C\|" substr($0,6,length($0)-5)}
  /:57B:/       {print NR "\|57B\|" substr($0,6,9)}
  /:59:/        {print NR "\|59\|" substr($0,5,9)}
  /:70:\/NUM\// {print NR "\|NUM\|" substr($0,10,length($0)-9)}
  /\/VO\//      {print NR "\|VO\|" substr($0,5,length($0)-4)}
  /\/DATE\//    {print NR "\|DATE\|"substr($0,11,2) "." substr($0,9,2) "." substr($0,7,2)}
  /\/SEND\//    {print NR "\|SEND\|" substr($0,7,length($0)-6)}
  /\/KNP\//     {print NR "\|KNP\|" substr($0,6,length($0)-5)}
  /\/PSO\//     {print NR "\|PSO\|" substr($0,6,length($0)-5)} 
  /\/PRT\//     {print NR "\|PRT\|" substr($0,6,length($0)-5)}
  /\/ASSIGN\//  {while (substr($0,1,4)!=":21:") {
                if (substr($0,1,8)=="\/ASSIGN\/") {
                    print NR "\|ASSIGN\|" substr($0,9,length($0)-8)
                    }  
                          else { print NR "\|ASSIGN\|" $0}
                if (getline == 0) { exit }
               }
          }  
  /:32B:KZT/   {s = substr($0,9,length($0)-8); split (s,W,","); s = W[1] "." W[2]; sum = sum + s}
  /:32A:/ { s = substr($0,15,length($0)-14); split (s,W,","); s = W[1] "." W[2]
            printf ("%d\|AMT\|%.2f\n%d\|VDT\|%8s\n",NR, s,NR,substr($0,10,2) "." substr($0,8,2) "." substr($0,6,2))}
 END { printf ("%d\|SUM\|%.2f\n",NR,sum) }
 ' | tr '\042' '\047' > /tmp/$1.hdh  

PEREM=`tail -c 2 /tmp/$1.txt`                                                                                                                    
if test "$PEREM" = "-}"                                                                                                                   
then                                                                                                                                
 echo > /tmp/tmp_pf
 cat /tmp/$1.txt /tmp/tmp_pf > /tmp/$1.tmp
 rm -f /tmp/tmp_pf
 rm -f /tmp/$1.txt
else
 mv -f /tmp/$1.txt /tmp/$1.tmp
fi                                                                                                                                  

cat /tmp/$1.tmp | tr -d '\015' | sed '1c\
{1:F01K059140000000001000001}
2c\
{2:I102SGROSS000000U3003}
3c\
{4:
4c\
:20:REFERENCE
' | alt2koi > /tmp/$1.txt
#rm -f /tmp/$1.tmp
